# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60580c5fa058569f360fcf9cb8d51ca3953aaedd306e4e5ecf96d7954e41f3d85c45a0afaf0048226f9fcfcc276bc5449335487ef7867ae3d683c432a716c970

test:
  secret_key_base: 762d47cf0dbbcfe661445e680e6c90e5a26e9fbc02f81b7d85c455a221229b883ea874c007ca7e0e9345986f6a144cd8855f96cb66c5c632fafeb70048607190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
